# Generated by Django 5.1.3 on 2024-11-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
